-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM
(
SELECT I.ANIMAL_ID, I.NAME, DATEDIFF(O.DATETIME, I.DATETIME)
FROM ANIMAL_INS AS I INNER JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY 3 DESC
LIMIT 2
) A