-- 코드를 입력하세요
SELECT UU.USER_ID, UU.NICKNAME,
CONCAT(UU.CITY," ",UU.STREET_ADDRESS1," ",UU.STREET_ADDRESS2) AS "전체주소",
CONCAT(SUBSTRING(UU.TLNO, 1, 3), "-", SUBSTRING(UU.TLNO, 4, 4), "-", SUBSTRING(UU.TLNO, 8,4)) AS "전화번호"
FROM USED_GOODS_BOARD AS UB LEFT JOIN USED_GOODS_USER AS UU ON UB.WRITER_ID = UU.USER_ID
GROUP BY 1,2,3
HAVING COUNT(UB.WRITER_ID) >= 3
ORDER BY 1 DESC