-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT AS P 
INNER JOIN APPOINTMENT AS A ON P.PT_NO = A.PT_NO
INNER JOIN DOCTOR AS D ON D.DR_ID = A.MDDR_ID
WHERE MONTH(A.APNT_YMD) = 04 
AND DAY(A.APNT_YMD) = 13 
AND A.MCDP_CD = 'CS'
AND A.APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD ASC