-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, TOTAL_SALES
FROM
(
SELECT U.USER_ID, U.NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS B INNER JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
WHERE B.STATUS = 'DONE'
GROUP BY 1
) A
WHERE TOTAL_SALES >= 700000
GROUP BY 1
ORDER BY TOTAL_SALES ASC;