-- 코드를 입력하세요
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, 
CASE WHEN UG.STATUS = 'SALE' THEN '판매중'
     WHEN UG.STATUS = 'RESERVED' THEN '예약중'
     WHEN UG.STATUS = 'DONE' THEN '거래완료'
     ELSE NULL
     END AS STATUS
FROM USED_GOODS_BOARD AS UG
WHERE YEAR(CREATED_DATE) = 2022 AND MONTH(CREATED_DATE) = 10 AND DAY(CREATED_DATE) = 5
ORDER BY 1 DESC